version: '1'
services:
  ssl-spring:
    container_name: ssl-spring
    build:
      context: .
      dockerfile: Dockerfile
    image: ssl-spring:latest
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - ssl-spring-network
networks:
  ssl-spring-network:
    driver: bridge
